all:
	zip zadanie.zip \
	    doc/*.tex doc/Makefile doc/Wykresy/* doc/sprawozdanie.pdf \
			prog/*.cpp prog/*.h prog/README prog/CMakeLists.txt prog/tests/*.py \
      prog/tests/Makefile prog/unittests/*.py
